featureList = [
    "add",
    "sub",
    "xor",
    "mult",
    "a = 0",
    "b = 0",
    "a = ffffffff",
    "b = ffffffff",
    "a < 0",
    "b < 0",
    "a > 0",
    "b > 0",
    "ass < 0",
    "bs < 0",
    "ass > 0",
    "bs > 0",
    "unsigned overflow",
    "signed overflow",
    "negative sub result",
    "xor zero",
    "xor all ones",
    "zero mult result",
    "jump",
    "data bypass"
]